
server:
  port: 9999
#  servlet:
#    context-path: /sanima



spring:
  jpa:

    show-sql: true
    hibernate:
      ddl-auto: update
#      ddl-auto: create-drop
    properties:
      hibernate.jdbc.batch_size: 20
      hibernate.cache.use_query_cache: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_structured_entries: false
      hibernate.cache.use_minimal_puts: false
  datasource:
    url: jdbc:postgresql://localhost:5432/sanima_poc
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


springfox:
  documentation:
    auto-startup: false

